# All jobs here are testing using openjdk10, no oracle jdk used since
# most are deprecated
jobs:
  include:
    - os: linux
      language: java
      jdk: openjdk10
      script: chmod +x ./gradlew && ./gradlew build
    - os: osx
      language: java
      jdk: openjdk10
      script: chmod +x ./gradlew && ./gradlew build
    # Windows does not support java, thus we customize our script
    # Windows allows download of jdk8, so we can test on it
    - os: windows
      language: shell
      script: sh win_gradle_setuprun.sh

install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/